version: '2.6'
services:
  central: 
    build: ./central 
    ports:
      - 8090:8090

  client:
    build: ./client
    network_mode: host
    depends_on:
      - central
  
  client2:
    build: ./client2
    network_mode: host
    depends_on:
      - central
  client3:
    build: ./client3
    network_mode: host
    depends_on:
      - central
  client4:
    build: ./client4
    network_mode: host
    depends_on:
      - central